name: gitfy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  flukit: ^3.0.1
  dynamic_color: ^1.4.0
  url_launcher: ^6.1.5
  json_annotation: ^4.1.0
  shared_preferences: ^2.0.15
  package_info: ^2.0.2
  dio: ^4.0.6
  font_awesome_flutter: ^10.1.0
  path_provider: ^2.0.11
  flutter_markdown: ^0.6.10+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_model: ^1.0.0
  json_serializable: ^5.0.0
  test: ^1.20.2

flutter_intl:
  enabled: true
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true


